name 'rifiniti'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rifiniti'
long_description 'Installs/Configures rifiniti'
version '0.1.0'

depends 'java'
depends 'maven'